version: "3.7"
services:
    api:
        image: docker.pkg.github.com/fffnite/go-oneroster/goors:0.3.1
        environment:
            GOORS_MONGO_URI: mongodb://database
        env_file:
          - .env
        depends_on:
          - database
        labels:
          - traefik.enable=true
          - traefik.http.routers.goors.tls=true
            # Set domain name for your domain
          - traefik.http.routers.goors.rule=Host(`or.localhost`)
    database:
        image: mongo
        volumes:
            # Set database directory to non temp folder
            - /tmp/data/db:/data/db
    reverse-proxy:
        image: traefik
        ports:
          - 443:443
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./traefik/traefik.toml:/etc/traefik/traefik.toml
            # Add your ssl ,crt and .key files to ./traefik/cert
          - ./traefik/cert:/cert
