version: "3.7"

networks:
  default:
      name: webproxy

services:
    api:
        build: 
          context: .
        environment:
            USULROSTER_MONGO_URI: mongodb://database
        env_file:
          - .env
        ports:
         - 9543:80
        
        restart: always
        depends_on:
          - database
        labels:
          - "traefik.enable=false"
          #- traefik.http.routers.api.tls=true
            # Set domain name for your domain
          #- "traefik.http.routers.api.rule=Host(`api.pleasedwork.local`)" #Host("or.localhost")
    database:
        image: mongo
        restart: always
        volumes:
            # Set database directory to non temp folder
            - mongodata:/data/db

    #reverse-proxy:
    #    image: traefik
    #    command: --api.insecure=true --providers.docker
    #    ports:
          # The HTTP port
    #      - "80:80"
          # The Web UI (enabled by --api.insecure=true)
    #      - "8080:8080"
    #    volumes:
    #      - /var/run/docker.sock:/var/run/docker.sock
        #  - ./traefik/traefik.toml:/etc/traefik/traefik.toml
            # Add your ssl ,crt and .key files to ./traefik/cert
        #  - ./traefik/cert:/cert

volumes:
  mongodata:

