[providers]
    [providers.file]
        filename = "/etc/traefik/traefik.toml"
    [providers.docker]

[entryPoints]
    [entryPoints.web]
        address = ":9543"

[tls.stores.default.defaultCertificate]
    certFile = "/etc/letsencrypt/live/api.usul.academy/fullchain.pem"
    keyFile = "/etc/letsencrypt/live/api.usul.academy/privkey.pem"
